### PR TITLE
Update README.md about AUR instructions

### PR DESCRIPTION
**Pull request by orhun**
Hey,
I'm an [Arch Linux](https://aur.archlinux.org) package [maintainer](https://github.com/orhun/PKGBUILDs). I'm submitting this PR to let you know that I created the following packages for the installation of `termchat` on Arch Linux and other distributions that support installing packages from [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository):

* [termchat](https://aur.archlinux.org/packages/termchat/) (builds from source)
* [termchat-git](https://aur.archlinux.org/packages/termchat-git/) (VCS/development package)

PS: I can create a `-bin` package if you provide a pre-compiled x86_64 binary along with the release artifacts.

I also updated README.md about installation from AUR. (bec49a2)

Regards,
orhun.

### CODE REVIEW

**Comment by sigmaSd** [comment]
Hi,
Just a small correction the current version is 1.0.0 not 0.1.0
About the bin release, this should be possible once https://github.com/lemunozm/termchat/pull/13 lands

**Comment by orhun** [comment]
> Just a small correction the current version is 1.0.0 not 0.1.0

The most recent [tag](https://github.com/lemunozm/termchat/tags) is `0.1.0` A new tag/release should be created for `termchat` package to be updated.

On the other hand, `termchat-git` uses the latest state of the repository. (eg: `0.1.0.r13.g4c764c2-1` -> tag: `0.1.0`, revision: `13`, commit: `4c764c2`)

**Comment by lemunozm** [comment]
Thank you so much!!

I will upload the 1.0.0 version tag ASAP. I will notify you by this PR for creating the bin release :)

**Comment by lemunozm** [comment]
The binary releases are up. Thanks!!

**Comment by orhun** [comment]
https://aur.archlinux.org/packages/termchat-bin/ 🥂

**Pull request merged**
